In [1]:
#importing
import numpy as np
#create array using array() function
myarray1= np.array([(1,2,3),(4,5,6),(7,8,9),(10,11,12)])#1x4 array 
print(myarray1)
print("\n")

#array to list and list to array.
list_ex=[1,2,3,4,5]
myarray2 = np.array(list_ex)
array_ex = [6,7,8,9,10]
mylist = list(array_ex)

print(myarray2)
print(mylist)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[1 2 3 4 5]
[6, 7, 8, 9, 10]


In [34]:
#numpy basic operations
a= np.array([1,2,3])
b= np.array([4,5,6]) # for summition and substruction the size of arrays must be equal.

print(a+b) #[5 7 9]
print(a-b) #[-3 -3 -3]
print(a**2) #[1 4 9]

[5 7 9]
[-3 -3 -3]
[1 4 9]


In [49]:
#print array.
a=myarray1
print(a)
print('\n')
print(a[0])
print('\n')
print(a[0:2])
print('\n')
print(a[::-1])
print('\n')
print(a[1,1]) 
print('\n')
print(a[:,1]) 
print('\n')
print(a[1,:]) 
print('\n')
print(a[1,1:4]) 
print('\n')
print(a[-1,:]) 
print('\n')
print(a[:,-1]) 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[1 2 3]


[[1 2 3]
 [4 5 6]]


[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]]


5


[ 2  5  8 11]


[4 5 6]


[5 6]


[10 11 12]


[ 3  6  9 12]


In [9]:
np.empty((2,3))#create empty array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
#shape-reshape-dimension-data_type-size-type
#shape:
print('shape:',myarray1.shape)
print('\n')
#reshape:
print('reshape:\n',myarray1.reshape(6,2))
print('\n')
print('dimension:',myarray1.ndim)
print('\n')
print('data type:',myarray1.dtype)
print('\n')
print('size:',myarray1.size)
print('\n')
print('type:',type(myarray1))
print('\n')

shape: (4, 3)


reshape:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


dimension: 2


data type: int32


size: 12


type: <class 'numpy.ndarray'>




In [32]:
#arange
#print the numbers between 0 and 20 two by two 
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
#linspace
#print 20 numbers each 0 and 10
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [51]:
#transpose
print(myarray1.T)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [54]:
#ravel methoduyla tek boyutlu hale getirilir.
myarray3= np.array([(1,2,3),(4,5,6),(7,8,9),(10,11,12)])
a=myarray3.ravel()
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
